version: 2

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-osx
      - build-linux

jobs:
  build-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: "echo 'hello osx'"
      - *build-and-test

  build-linux:
    machine: true
    steps:
      - checkout
      - run: "echo 'hello linux'"
      - *build-and-test

&build-and-test
      run:
        name: Build and test
        command: ./test/all.sh;
